Sapm Classification Dataset and by solving, experimenting with Machine Learning Models.

Steps:

- Text Preprocessing

  Tokenization

  Stopwords

  Stemming

  Lemmatization

- Converting Text into Vectors

  Bag of Words

  TF-IDF

  Word2Vec

  Average Word 2 Vec

- All these are implemented by using Python & Machine Learning.


In [1]:
!pip install numpy==1.21.6


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.9/15.9 MB 62.9 MB/s eta 0:00:00
  Attempting uninstall: numpy
    Found existing installation: numpy 1.25.2
    Uninstalling numpy-1.25.2:
      Successfully uninstalled numpy-1.25.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
chex 0.1.85 requires numpy>=1.24.1, but you have numpy 1.21.6 which is incompatible.
flax 0.8.1 requires numpy>=1.22, but you have numpy 1.21.6 which is incompatible.
jax 0.4.23 requires numpy>=1.22, but you have numpy 1.21.6 which is incompatible.
jaxlib 0.4.23+cuda12.cudnn89 requires numpy>=1.22, but you have numpy 1.21.6 which is incompatible.
numba 0.58.1 requires numpy<1.27,>=1.22, but you have numpy 1.21.6 which is incompatible.
plotnine 0.12.4 requires numpy>=1.23.0, but you have numpy 1.21.6 which is incompatible.
pywavelets 1.5.0 requires numpy<2.0,>=1.22.4, but you have numpy 

In [1]:
import pandas as pd
import numpy as np


In [2]:
messages=pd.read_csv("/content/SMSSpamCollection",sep="\t",names=["label","message"])

In [3]:
messages

label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [4]:
messages.shape

(5572, 2)

In [5]:
messages.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   label    5572 non-null   object
 1   message  5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB


In [6]:
messages["message"].loc[88]

"I'm really not up to it still tonight babe"

Data Cleaning & Preprocessing

In [7]:
import re       # Regular Expression
import nltk
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [8]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [9]:
from nltk.corpus import stopwords

corpus=[]
for i in range(0,len(messages)):
  review=re.sub("[^a-zA-Z0-9]"," ",messages["message"][i])
  review=review.lower()
  review=review.split()

  review=[ps.stem(word) for word in review if not word in stopwords.words("english")]
  review=" ".join(review)
  corpus.append(review)

In [10]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri 2 wkli comp win fa cup final tkt 21st may 2005 text fa 87121 receiv entri question std txt rate c appli 08452810075over18',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl 3 week word back like fun still tb ok xxx std chg send 1 50 rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press 9 copi friend callertun',
 'winner valu network custom select receivea 900 prize reward claim call 09061701461 claim code kl341 valid 12 hour',
 'mobil 11 month u r entitl updat latest colour mobil camera free call mobil updat co free 08002986030',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash 100 20 000 pound txt csh11 send 87575 cost 150p day 6day 16 tsandc appli repli hl 4 info',
 'urgent 1 week free mem

Initializing the Bag of Words Model

In [11]:
from sklearn.feature_extraction .text import CountVectorizer
cv=CountVectorizer(max_features=2500,ngram_range=(2,2),binary=True)
X=cv.fit_transform(corpus).toarray()

In [12]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [13]:
X.shape

(5572, 2500)

In [14]:
y=pd.get_dummies(messages["label"])
y=y.iloc[:,1].values

In [15]:
y

array([0, 0, 1, ..., 0, 0, 0], dtype=uint8)

Splitting the data into Training & Testing

In [16]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=0)


In [17]:
X_train,y_train

(array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]),
 array([0, 0, 0, ..., 1, 0, 0], dtype=uint8))

In [18]:
from sklearn.naive_bayes import MultinomialNB
spam_detect_model=MultinomialNB().fit(X_train,y_train)

In [19]:
y_pred=spam_detect_model.predict(X_test)

In [20]:
from sklearn.metrics import accuracy_score,classification_report

In [21]:
score=accuracy_score(y_test,y_pred).mean()*100
print(score)

97.21973094170404


In [22]:
from sklearn.metrics import accuracy_score,classification_report
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       1.00      0.97      0.98       986
           1       0.81      1.00      0.89       129

    accuracy                           0.97      1115
   macro avg       0.90      0.98      0.94      1115
weighted avg       0.98      0.97      0.97      1115



TF - IDF Vector Model

In [23]:
from sklearn.feature_extraction.text import TfidfVectorizer
tv=TfidfVectorizer(max_features=2700,ngram_range=(1,2),binary=True)
X=tv.fit_transform(corpus).toarray()

Splitting the Data into Training & Testing

In [24]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)


In [25]:
from sklearn.naive_bayes import MultinomialNB
spam_detect_model=MultinomialNB().fit(X_train,y_train)

In [26]:
y_pred=spam_detect_model.predict(X_test)

In [27]:
score=accuracy_score(y_test,y_pred)

In [28]:
score

0.9838565022421525

In [29]:
from sklearn.metrics import classification_report
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       1.00      0.98      0.99       973
           1       0.89      1.00      0.94       142

    accuracy                           0.98      1115
   macro avg       0.94      0.99      0.97      1115
weighted avg       0.99      0.98      0.98      1115



# **Word 2 Vec Implementation**

In [30]:
!pip install gensim

In [31]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...


True

In [32]:
from nltk.stem import WordNetLemmatizer
lemmatizer=WordNetLemmatizer()

In [33]:
from nltk.corpus import stopwords

corpus=[]
for i in range(0,len(messages)):
  review=re.sub("[^a-zA-Z0-9]"," ",messages["message"][i])
  review=review.lower()
  review=review.split()

  review=[lemmatizer.lemmatize(word) for word in review if not word in stopwords.words("english")]
  review=" ".join(review)
  corpus.append(review)

In [34]:
corpus

['go jurong point crazy available bugis n great world la e buffet cine got amore wat',
 'ok lar joking wif u oni',
 'free entry 2 wkly comp win fa cup final tkts 21st may 2005 text fa 87121 receive entry question std txt rate c apply 08452810075over18',
 'u dun say early hor u c already say',
 'nah think go usf life around though',
 'freemsg hey darling 3 week word back like fun still tb ok xxx std chgs send 1 50 rcv',
 'even brother like speak treat like aid patent',
 'per request melle melle oru minnaminunginte nurungu vettam set callertune caller press 9 copy friend callertune',
 'winner valued network customer selected receivea 900 prize reward claim call 09061701461 claim code kl341 valid 12 hour',
 'mobile 11 month u r entitled update latest colour mobile camera free call mobile update co free 08002986030',
 'gonna home soon want talk stuff anymore tonight k cried enough today',
 'six chance win cash 100 20 000 pound txt csh11 send 87575 cost 150p day 6days 16 tsandcs apply reply

In [35]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [36]:
corpus[8]

'winner valued network customer selected receivea 900 prize reward claim call 09061701461 claim code kl341 valid 12 hour'

In [37]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [38]:
words=[]
for sent in corpus:
  sent_token=sent_tokenize(sent)
  for sent in sent_token:
    words.append(simple_preprocess(sent))

In [39]:
words

[['go',
  'jurong',
  'point',
  'crazy',
  'available',
  'bugis',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'got',
  'amore',
  'wat'],
 ['ok', 'lar', 'joking', 'wif', 'oni'],
 ['free',
  'entry',
  'wkly',
  'comp',
  'win',
  'fa',
  'cup',
  'final',
  'tkts',
  'st',
  'may',
  'text',
  'fa',
  'receive',
  'entry',
  'question',
  'std',
  'txt',
  'rate',
  'apply',
  'over'],
 ['dun', 'say', 'early', 'hor', 'already', 'say'],
 ['nah', 'think', 'go', 'usf', 'life', 'around', 'though'],
 ['freemsg',
  'hey',
  'darling',
  'week',
  'word',
  'back',
  'like',
  'fun',
  'still',
  'tb',
  'ok',
  'xxx',
  'std',
  'chgs',
  'send',
  'rcv'],
 ['even', 'brother', 'like', 'speak', 'treat', 'like', 'aid', 'patent'],
 ['per',
  'request',
  'melle',
  'melle',
  'oru',
  'minnaminunginte',
  'nurungu',
  'vettam',
  'set',
  'callertune',
  'caller',
  'press',
  'copy',
  'friend',
  'callertune'],
 ['winner',
  'valued',
  'network',
  'customer',
  'selected',
  're

In [40]:
import gensim

In [41]:
model=gensim.models.Word2Vec(words,window=5,min_count=2)

In [42]:
model.wv.index_to_key

['call',
 'get',
 'ur',
 'gt',
 'go',
 'lt',
 'ok',
 'day',
 'free',
 'know',
 'come',
 'like',
 'good',
 'time',
 'got',
 'text',
 'love',
 'want',
 'send',
 'need',
 'one',
 'txt',
 'today',
 'going',
 'stop',
 'home',
 'lor',
 'sorry',
 'see',
 'still',
 'mobile',
 'take',
 'back',
 'da',
 'reply',
 'dont',
 'think',
 'tell',
 'week',
 'phone',
 'hi',
 'new',
 'later',
 'please',
 'pls',
 'co',
 'msg',
 'make',
 'dear',
 'night',
 'message',
 'well',
 'say',
 'min',
 'thing',
 'much',
 'great',
 'claim',
 'hope',
 'oh',
 'hey',
 'give',
 'number',
 'happy',
 'friend',
 'work',
 'wat',
 'way',
 'yes',
 'www',
 'let',
 'prize',
 'right',
 'tomorrow',
 'already',
 'ask',
 'said',
 'win',
 'amp',
 'life',
 'cash',
 'yeah',
 'im',
 'tone',
 'really',
 'babe',
 'meet',
 'find',
 'miss',
 'morning',
 'uk',
 'last',
 'service',
 'thanks',
 'care',
 'com',
 'would',
 'anything',
 'year',
 'also',
 'lol',
 'nokia',
 'every',
 'feel',
 'keep',
 'sure',
 'pick',
 'urgent',
 'contact',
 'sent',


In [43]:
model.corpus_count

5565

In [44]:
model.epochs

5

In [45]:
model.wv.similar_by_word("bold")

[('quite', 0.9888458847999573),
 ('etc', 0.9888125061988831),
 ('available', 0.988727331161499),
 ('though', 0.9886029362678528),
 ('fine', 0.9885817170143127),
 ('true', 0.9884914755821228),
 ('someone', 0.9884309768676758),
 ('yr', 0.9884039759635925),
 ('hw', 0.9883264303207397),
 ('cum', 0.9883072972297668)]

In [46]:
def avg_word2vec(doc):
    return np.mean([model.wv[word] for word in doc if word in model.wv.index_to_key],axis=0)

In [47]:
!pip install tqdm

In [48]:
from tqdm import tqdm

In [49]:
words[83]

['place', 'man']

In [50]:
type(model.wv.index_to_key)

list

In [51]:
words

[['go',
  'jurong',
  'point',
  'crazy',
  'available',
  'bugis',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'got',
  'amore',
  'wat'],
 ['ok', 'lar', 'joking', 'wif', 'oni'],
 ['free',
  'entry',
  'wkly',
  'comp',
  'win',
  'fa',
  'cup',
  'final',
  'tkts',
  'st',
  'may',
  'text',
  'fa',
  'receive',
  'entry',
  'question',
  'std',
  'txt',
  'rate',
  'apply',
  'over'],
 ['dun', 'say', 'early', 'hor', 'already', 'say'],
 ['nah', 'think', 'go', 'usf', 'life', 'around', 'though'],
 ['freemsg',
  'hey',
  'darling',
  'week',
  'word',
  'back',
  'like',
  'fun',
  'still',
  'tb',
  'ok',
  'xxx',
  'std',
  'chgs',
  'send',
  'rcv'],
 ['even', 'brother', 'like', 'speak', 'treat', 'like', 'aid', 'patent'],
 ['per',
  'request',
  'melle',
  'melle',
  'oru',
  'minnaminunginte',
  'nurungu',
  'vettam',
  'set',
  'callertune',
  'caller',
  'press',
  'copy',
  'friend',
  'callertune'],
 ['winner',
  'valued',
  'network',
  'customer',
  'selected',
  're

In [52]:
X=[]
for i in tqdm(range(len(words))):
  X.append(avg_word2vec(words[i]))

  0%|          | 0/5565 [00:00<?, ?it/s]/usr/local/lib/python3.10/dist-packages/numpy/core/fromnumeric.py:3440: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/usr/local/lib/python3.10/dist-packages/numpy/core/_methods.py:189: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
100%|██████████| 5565/5565 [00:01<00:00, 2891.83it/s]


In [53]:
type(X)


list

In [54]:
import numpy as np

In [55]:
X_new=np.array(X)

<ipython-input-55-1dbb21e0886e>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  X_new=np.array(X)


In [56]:
words[0]

['go',
 'jurong',
 'point',
 'crazy',
 'available',
 'bugis',
 'great',
 'world',
 'la',
 'buffet',
 'cine',
 'got',
 'amore',
 'wat']

In [57]:
X_new[0]

array([-0.09886695,  0.30202666,  0.04265255,  0.0337358 , -0.00189229,
       -0.38450107,  0.0654422 ,  0.5373669 , -0.14970021, -0.10006159,
       -0.11203185, -0.40146002, -0.04004082,  0.05986867,  0.07894462,
       -0.24143423, -0.00354546, -0.35621953, -0.04321182, -0.4118947 ,
        0.14467435,  0.01892582,  0.11891171, -0.12570046, -0.15777703,
        0.01511166, -0.28578305, -0.26957688, -0.22202545,  0.07515761,
        0.27543083,  0.04029712,  0.10735323, -0.1557662 , -0.1376242 ,
        0.22905867, -0.05947802, -0.27179882, -0.1841567 , -0.4684776 ,
       -0.00109299, -0.28643802, -0.003577  ,  0.02682201,  0.20983082,
       -0.14372511, -0.20142375,  0.00078968,  0.12403091,  0.16270873,
        0.13127302, -0.24850364, -0.05005719, -0.05370576, -0.17578375,
        0.11664791,  0.13683917,  0.02251978, -0.26482055,  0.01152887,
        0.01727204,  0.12303856, -0.13256279,  0.02261163, -0.3378297 ,
        0.27997038,  0.12303799,  0.26444185, -0.33629107,  0.33

In [58]:
X_new.shape

(5565,)

In [59]:
X_new

array([array([-0.09886695,  0.30202666,  0.04265255,  0.0337358 , -0.00189229,
              -0.38450107,  0.0654422 ,  0.5373669 , -0.14970021, -0.10006159,
              -0.11203185, -0.40146002, -0.04004082,  0.05986867,  0.07894462,
              -0.24143423, -0.00354546, -0.35621953, -0.04321182, -0.4118947 ,
               0.14467435,  0.01892582,  0.11891171, -0.12570046, -0.15777703,
               0.01511166, -0.28578305, -0.26957688, -0.22202545,  0.07515761,
               0.27543083,  0.04029712,  0.10735323, -0.1557662 , -0.1376242 ,
               0.22905867, -0.05947802, -0.27179882, -0.1841567 , -0.4684776 ,
              -0.00109299, -0.28643802, -0.003577  ,  0.02682201,  0.20983082,
              -0.14372511, -0.20142375,  0.00078968,  0.12403091,  0.16270873,
               0.13127302, -0.24850364, -0.05005719, -0.05370576, -0.17578375,
               0.11664791,  0.13683917,  0.02251978, -0.26482055,  0.01152887,
               0.01727204,  0.12303856, -0.13256279,

In [60]:
X_new.shape

(5565,)